In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.2.1.tar.gz (281.4 MB)
     |████████████████████████████████| 281.4 MB 34 kB/s
Collecting py4j==0.10.9.3
  Downloading py4j-0.10.9.3-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 49.8 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.1-py2.py3-none-any.whl size=281853642 sha256=938601944add43553d96713ff64c7f6fd4d0da55ff86f1acc010caf9a1aabbe4
  Stored in directory: /root/.cache/pip/wheels/9f/f5/07/7cd8017084dce4e93e84e92efd1e1d5334db05f2e83bcef74f
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.3 pyspark-3.2.1

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
matplotlib.style.use('ggplot')

In [ ]:
df = pd.read_csv('callback_grains.csv')

In [ ]:
df['Attribute_Description'].nunique()

17

In [ ]:
dfe = df.pivot(index = ['Commodity_Code', 'Commodity_Description', 'Country_Name', 'Market_Year'], columns = 'Attribute_Description', values = 'Value')

In [ ]:
dfe

Attribute_Description                                          Area Harvested  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                 2230.0
                                                  1961                 2230.0
                                                  1962                 2341.0
                                                  1963                 2341.0
                                                  1964                 2345.0
...                                                                       ...
459900         Mixed Grain           Turkey       2008                    3.0
                                                  2009                    3.0
                                                  2010                    2.0
                                                  2011                    1.0
                                                  2012                    1.0

Attribute_Description                                          Beginning Stocks  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                      0.0
                                                  1961                      0.0
                                                  1962                      0.0
                                                  1963                      0.0
                                                  1964                      0.0
...                                                                         ...
459900         Mixed Grain           Turkey       2008                      0.0
                                                  2009                      0.0
                                                  2010                      0.0
                                                  2011                      0.0
                                                  2012                      0.0

Attribute_Description                                          Domestic Consumption  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                       2330.0
                                                  1961                       2294.0
                                                  1962                       2286.0
                                                  1963                       2027.0
                                                  1964                       2310.0
...                                                                             ...
459900         Mixed Grain           Turkey       2008                          3.0
                                                  2009                          4.0
                                                  2010                          2.0
                                                  2011                          1.0
                                                  2012                          1.0

Attribute_Description                                          Ending Stocks  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                   0.0
                                                  1961                   0.0
                                                  1962                   0.0
                                                  1963                   0.0
                                                  1964                   0.0
...                                                                      ...
459900         Mixed Grain           Turkey       2008                   0.0
                                                  2009                   0.0
                                                  2010                   0.0
                                                  2011                   0.0
                                                  2012                   0.0

Attribute_Description                                          Exports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960             0.0
                                                  1961             0.0
                                                  1962             0.0
                                                  1963             0.0
                                                  1964             0.0
...                                                                ...
459900         Mixed Grain           Turkey       2008             0.0
                                                  2009             0.0
                                                  2010             0.0
                                                  2011             0.0
                                                  2012             0.0

Attribute_Description                                          FSI Consumption  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                  2330.0
                                                  1961                  2294.0
                                                  1962                  2286.0
                                                  1963                  2027.0
                                                  1964                  2310.0
...                                                                        ...
459900         Mixed Grain           Turkey       2008                     0.0
                                                  2009                     0.0
                                                  2010                     0.0
                                                  2011                     0.0
                                                  2012                     0.0

Attribute_Description                                          Feed Dom. Consumption  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                           0.0
                                                  1961                           0.0
                                                  1962                           0.0
                                                  1963                           0.0
                                                  1964                           0.0
...                                                                              ...
459900         Mixed Grain           Turkey       2008                           3.0
                                                  2009                           4.0
                                                  2010                           2.0
                                                  2011                           1.0
                                                  2012                           1.0

Attribute_Description                                          Imports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960            51.0
                                                  1961            15.0
                                                  1962             7.0
                                                  1963            80.0
                                                  1964            60.0
...                                                                ...
459900         Mixed Grain           Turkey       2008             0.0
                                                  2009             0.0
                                                  2010             0.0
                                                  2011             0.0
                                                  2012             0.0

Attribute_Description                                          Milling Rate (.9999)  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                          NaN
                                                  1961                          NaN
                                                  1962                          NaN
                                                  1963                          NaN
                                                  1964                          NaN
...                                                                             ...
459900         Mixed Grain           Turkey       2008                          NaN
                                                  2009                          NaN
                                                  2010                          NaN
                                                  2011                          NaN
                                                  2012                          NaN

Attribute_Description                                          Production  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960             2279.0
                                                  1961             2279.0
                                                  1962             2279.0
                                                  1963             1947.0
                                                  1964             2250.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008                3.0
                                                  2009                4.0
                                                  2010                2.0
                                                  2011                1.0
                                                  2012                1.0

Attribute_Description                                          Rough Production  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                      NaN
                                                  1961                      NaN
                                                  1962                      NaN
                                                  1963                      NaN
                                                  1964                      NaN
...                                                                         ...
459900         Mixed Grain           Turkey       2008                      NaN
                                                  2009                      NaN
                                                  2010                      NaN
                                                  2011                      NaN
                                                  2012                      NaN

Attribute_Description                                          TY Exports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                0.0
                                                  1961                0.0
                                                  1962                0.0
                                                  1963                0.0
                                                  1964                0.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008                0.0
                                                  2009                0.0
                                                  2010                0.0
                                                  2011                0.0
                                                  2012                0.0

Attribute_Description                                          TY Imp. from U.S.  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                      46.0
                                                  1961                      15.0
                                                  1962                       7.0
                                                  1963                      56.0
                                                  1964                      52.0
...                                                                          ...
459900         Mixed Grain           Turkey       2008                       0.0
                                                  2009                       0.0
                                                  2010                       0.0
                                                  2011                       0.0
                                                  2012                       0.0

Attribute_Description                                          TY Imports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960               51.0
                                                  1961               15.0
                                                  1962                7.0
                                                  1963               80.0
                                                  1964               60.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008                0.0
                                                  2009                0.0
                                                  2010                0.0
                                                  2011                0.0
                                                  2012                0.0

Attribute_Description                                          Total Distribution  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                     2330.0
                                                  1961                     2294.0
                                                  1962                     2286.0
                                                  1963                     2027.0
                                                  1964                     2310.0
...                                                                           ...
459900         Mixed Grain           Turkey       2008                        3.0
                                                  2009                        4.0
                                                  2010                        2.0
                                                  2011                        1.0
                                                  2012                        1.0

Attribute_Description                                          Total Supply  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960               2330.0
                                                  1961               2294.0
                                                  1962               2286.0
                                                  1963               2027.0
                                                  1964               2310.0
...                                                                     ...
459900         Mixed Grain           Turkey       2008                  3.0
                                                  2009                  4.0
                                                  2010                  2.0
                                                  2011                  1.0
                                                  2012                  1.0

Attribute_Description                                          Yield
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960          1.02
                                                  1961          1.02
                                                  1962          0.97
                                                  1963          0.83
                                                  1964          0.96
...                                                              ...
459900         Mixed Grain           Turkey       2008          1.00
                                                  2009          1.33
                                                  2010          1.00
                                                  2011          1.00
                                                  2012          1.00

[26408 rows x 17 columns]

In [ ]:
dfe['Exports'] *= 1000
dfe['Imports'] *= 1000
dfe['Area Harvested'] *= 1000
dfe['Beginning Stocks'] *= 1000
dfe['Ending Stocks'] *= 1000
dfe['FSI Consumption'] *= 1000
dfe['Feed Dom. Consumption'] *= 1000
dfe['Production'] *= 1000
dfe['TY Exports'] *= 1000
dfe['TY Imp. from U.S.'] *= 1000
dfe['TY Imports'] *= 1000
dfe['Milling Rate (.9999)'] *= 1000
dfe['Rough Production'] *= 1000

In [ ]:
dfe2 = dfe.drop(['Domestic Consumption', 'Total Distribution', 'Total Supply', 'Yield'], axis = 1)

In [ ]:
dfe2

Attribute_Description                                          Area Harvested  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960              2230000.0
                                                  1961              2230000.0
                                                  1962              2341000.0
                                                  1963              2341000.0
                                                  1964              2345000.0
...                                                                       ...
459900         Mixed Grain           Turkey       2008                 3000.0
                                                  2009                 3000.0
                                                  2010                 2000.0
                                                  2011                 1000.0
                                                  2012                 1000.0

Attribute_Description                                          Beginning Stocks  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                      0.0
                                                  1961                      0.0
                                                  1962                      0.0
                                                  1963                      0.0
                                                  1964                      0.0
...                                                                         ...
459900         Mixed Grain           Turkey       2008                      0.0
                                                  2009                      0.0
                                                  2010                      0.0
                                                  2011                      0.0
                                                  2012                      0.0

Attribute_Description                                          Ending Stocks  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                   0.0
                                                  1961                   0.0
                                                  1962                   0.0
                                                  1963                   0.0
                                                  1964                   0.0
...                                                                      ...
459900         Mixed Grain           Turkey       2008                   0.0
                                                  2009                   0.0
                                                  2010                   0.0
                                                  2011                   0.0
                                                  2012                   0.0

Attribute_Description                                          Exports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960             0.0
                                                  1961             0.0
                                                  1962             0.0
                                                  1963             0.0
                                                  1964             0.0
...                                                                ...
459900         Mixed Grain           Turkey       2008             0.0
                                                  2009             0.0
                                                  2010             0.0
                                                  2011             0.0
                                                  2012             0.0

Attribute_Description                                          FSI Consumption  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960               2330000.0
                                                  1961               2294000.0
                                                  1962               2286000.0
                                                  1963               2027000.0
                                                  1964               2310000.0
...                                                                        ...
459900         Mixed Grain           Turkey       2008                     0.0
                                                  2009                     0.0
                                                  2010                     0.0
                                                  2011                     0.0
                                                  2012                     0.0

Attribute_Description                                          Feed Dom. Consumption  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                           0.0
                                                  1961                           0.0
                                                  1962                           0.0
                                                  1963                           0.0
                                                  1964                           0.0
...                                                                              ...
459900         Mixed Grain           Turkey       2008                        3000.0
                                                  2009                        4000.0
                                                  2010                        2000.0
                                                  2011                        1000.0
                                                  2012                        1000.0

Attribute_Description                                          Imports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960         51000.0
                                                  1961         15000.0
                                                  1962          7000.0
                                                  1963         80000.0
                                                  1964         60000.0
...                                                                ...
459900         Mixed Grain           Turkey       2008             0.0
                                                  2009             0.0
                                                  2010             0.0
                                                  2011             0.0
                                                  2012             0.0

Attribute_Description                                          Milling Rate (.9999)  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                          NaN
                                                  1961                          NaN
                                                  1962                          NaN
                                                  1963                          NaN
                                                  1964                          NaN
...                                                                             ...
459900         Mixed Grain           Turkey       2008                          NaN
                                                  2009                          NaN
                                                  2010                          NaN
                                                  2011                          NaN
                                                  2012                          NaN

Attribute_Description                                          Production  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960          2279000.0
                                                  1961          2279000.0
                                                  1962          2279000.0
                                                  1963          1947000.0
                                                  1964          2250000.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008             3000.0
                                                  2009             4000.0
                                                  2010             2000.0
                                                  2011             1000.0
                                                  2012             1000.0

Attribute_Description                                          Rough Production  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                      NaN
                                                  1961                      NaN
                                                  1962                      NaN
                                                  1963                      NaN
                                                  1964                      NaN
...                                                                         ...
459900         Mixed Grain           Turkey       2008                      NaN
                                                  2009                      NaN
                                                  2010                      NaN
                                                  2011                      NaN
                                                  2012                      NaN

Attribute_Description                                          TY Exports  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                0.0
                                                  1961                0.0
                                                  1962                0.0
                                                  1963                0.0
                                                  1964                0.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008                0.0
                                                  2009                0.0
                                                  2010                0.0
                                                  2011                0.0
                                                  2012                0.0

Attribute_Description                                          TY Imp. from U.S.  \
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960                   46000.0
                                                  1961                   15000.0
                                                  1962                    7000.0
                                                  1963                   56000.0
                                                  1964                   52000.0
...                                                                          ...
459900         Mixed Grain           Turkey       2008                       0.0
                                                  2009                       0.0
                                                  2010                       0.0
                                                  2011                       0.0
                                                  2012                       0.0

Attribute_Description                                          TY Imports
Commodity_Code Commodity_Description Country_Name Market_Year
410000         Wheat                 Afghanistan  1960            51000.0
                                                  1961            15000.0
                                                  1962             7000.0
                                                  1963            80000.0
                                                  1964            60000.0
...                                                                   ...
459900         Mixed Grain           Turkey       2008                0.0
                                                  2009                0.0
                                                  2010                0.0
                                                  2011                0.0
                                                  2012                0.0

[26408 rows x 13 columns]

In [ ]:
dfe2.to_csv('PSD_Grains_Final.csv')